### ISSUE TITLE
Custom Object Detection

### ISSUE THREAD

**Issue by nisarggandhewar** [TannerGilbert/Tutorials#31]
How can we use Tensorflow API for custom object detection. is it possible to train it for specific Object.

**Comment by TannerGilbert** [comment]
Yes. I actually have an step-by-step article on that topic: https://gilberttanner.com/blog/creating-your-own-objectdetector

**Comment by nisarggandhewar** [comment]
Thank for reply.
but while trying to install tensorflow object detection api on google
colab, I am getting following error.

ModuleNotFoundError: No module named 'tf_slim'

how to resolve it.

**Comment by nisarggandhewar** [comment]
I also resolve above error.
but while executing command

!python object_detection/builders/model_builder_test.py

I am getting Following error which I am not able to resolve


2020-05-27 10:21:51.849903: I
tensorflow/stream_executor/platform/default/dso_loader.cc:44]
Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 21, in <module>
    from object_detection.builders import model_builder
  File "/content/drive/My Drive/tesnsor
flow/models/research/object_detection/builders/model_builder.py", line
25, in <module>
    from object_detection.builders import matcher_builder
  File "/content/drive/My Drive/tesnsor
flow/models/research/object_detection/builders/matcher_builder.py",
line 19, in <module>
    from object_detection.matchers import bipartite_matcher
  File "/content/drive/My Drive/tesnsor
flow/models/research/object_detection/matchers/bipartite_matcher.py",
line 20, in <module>
    from tensorflow.contrib.image.python.ops import image_ops
ModuleNotFoundError: No module named 'tensorflow.contrib

I am using tesnfolw 2.2.0 on google colab, is it the case that it does
not works on 2.2 version.

**Comment by TannerGilbert** [comment]
If you want to train a custom model with the Tensorflow Object Detection API you need to use Tensorflow 1.x. 

You can install Tensorflow 1.x on Colab using the following commands:
 ```
!pip uninstall -y tensorflow tensorflow_gpu
!pip install tensorflow_gpu==1.13.1
```

**Comment by nisarggandhewar** [comment]
Ok thanks for reply,
I will try.

**Comment by nisarggandhewar** [comment]
As per your advice I have uninstall tensorflow 2.2 and install 1.13 version
and again run command

!python object_detection/builders/model_builder_test.py

but this time I am getting this error

File "/usr/local/lib/python3.6/dist-packages/tf_slim/layers/layers.py",
line 30, in <module>
    from tf_slim.ops import variables
  File "/usr/local/lib/python3.6/dist-packages/tf_slim/ops/variables.py",
line 27, in <module>
    from tensorflow.python.framework import device_spec as tf_device
ImportError: cannot import name 'device_spec'

kindly help me to resolve it.

**Comment by TannerGilbert** [comment]
Use the 1.13.0 branch instead of the master
```git clone https://github.com/tensorflow/models --single-branch --branch r1.13.0```

Check out my installation notebook for more information https://github.com/TannerGilbert/Tutorials/blob/master/Tensorflow%20Object%20Detection/Installing_the_Tensorflow_Object_Detection_API.ipynb

**Comment by nisarggandhewar** [comment]
thank, now it works.

**Comment by nisarggandhewar** [comment]
Dear Sir,
I am trying to train custom object detector using Google colab, After
removal of few error finally I Run this command to start training

!
python model_main.py --logtostderr --model_dir=training/
--pipeline_config_path=training/faster_rcnn_inception_v2_pets.config

I am getting following error. I have downgrade numpy to 1.17 and moved net
folder to object_detection.

InvalidArgumentError (see above for traceback): Found Inf or NaN global
norm. : Tensor had Inf values

	 [[node VerifyFinite/CheckNumerics (defined at
/usr/local/lib/python3.6/dist-packages/object_detection-0.1-py3.6.egg/object_detection/model_lib.py:382)
]]
	 [[node control_dependency (defined at
/usr/local/lib/python3.6/dist-packages/object_detection-0.1-py3.6.egg/object_detection/model_lib.py:382)
]]

Kindly help me to resolve this error.
I have check mismatch between .pbtxt file and tf record, everything is
fine.

**Comment by nisarggandhewar** [comment]
This is a detail execution

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:526:
FutureWarning: Passing (type, 1) or '1type' as a synonym of type is
deprecated; in a future version of numpy, it will be understood as
(type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:527:
FutureWarning: Passing (type, 1) or '1type' as a synonym of type is
deprecated; in a future version of numpy, it will be understood as
(type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:528:
FutureWarning: Passing (type, 1) or '1type' as a synonym of type is
deprecated; in a future version of numpy, it will be understood as
(type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:529:
FutureWarning: Passing (type, 1) or '1type' as a synonym of type is
deprecated; in a future version of numpy, it will be understood as
(type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:530:
FutureWarning: Passing (type, 1) or '1type' as a synonym of type is
deprecated; in a future version of numpy, it will be understood as
(type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:535:
FutureWarning: Passing (type, 1) or '1type' as a synonym of type is
deprecated; in a future version of numpy, it will be understood as
(type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:Forced number of epochs for all eval validations to be 1.
WARNING:tensorflow:Expected number of evaluation epochs is 1, but
instead encountered `eval_on_train_input_config.num_epochs` = 0.
Overwriting `num_epochs` to 1.
WARNING:tensorflow:Estimator's model_fn (<function
create_model_fn.<locals>.model_fn at 0x7fcefa975a60>) includes params
argument, but params are not passed to Estimator.
WARNING:tensorflow:From
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py:263:
colocate_with (from tensorflow.python.framework.ops) is deprecated and
will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:num_readers has been reduced to 1 to match input file shards.
WARNING:tensorflow:From
/usr/local/lib/python3.6/dist-packages/object_detection-0.1-py3.6.egg/object_detection/builders/dataset_builder.py:80:
parallel_interleave (from
tensorflow.contrib.data.python.ops.interleave_ops) is deprecated and
will be removed in a future version.
Instructions for updating:
Use `tf.data.experimental.parallel_interleave(...)`.
WARNING:tensorflow:From
/usr/local/lib/python3.6/dist-packages/object_detection-0.1-py3.6.egg/object_detection/anchor_generators/grid_anchor_generator.py:59:
to_float (from tensorflow.python.ops.math_ops) is deprecated and will
be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From
/usr/local/lib/python3.6/dist-packages/object_detection-0.1-py3.6.egg/object_detection/utils/ops.py:466:
to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will
be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From
/usr/local/lib/python3.6/dist-packages/object_detection-0.1-py3.6.egg/object_detection/builders/dataset_builder.py:148:
batch_and_drop_remainder (from
tensorflow.contrib.data.python.ops.batching) is deprecated and will be
removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.batch(..., drop_remainder=True)`.
WARNING:tensorflow:From
/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/layers/python/layers/layers.py:1624:
flatten (from tensorflow.python.layers.core) is deprecated and will be
removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:From
/usr/local/lib/python3.6/dist-packages/object_detection-0.1-py3.6.egg/object_detection/meta_architectures/faster_rcnn_meta_arch.py:2236:
get_or_create_global_step (from
tensorflow.contrib.framework.python.ops.variables) is deprecated and
will be removed in a future version.
Instructions for updating:
Please switch to tf.train.get_or_create_global_step
WARNING:root:Variable
[SecondStageBoxPredictor/BoxEncodingPredictor/biases] is available in
checkpoint, but has an incompatible shape with model variable.
Checkpoint shape: [[360]], model variable shape: [[4]]. This variable
will not be initialized from the checkpoint.
WARNING:root:Variable
[SecondStageBoxPredictor/BoxEncodingPredictor/weights] is available in
checkpoint, but has an incompatible shape with model variable.
Checkpoint shape: [[1024, 360]], model variable shape: [[1024, 4]].
This variable will not be initialized from the checkpoint.
WARNING:root:Variable [SecondStageBoxPredictor/ClassPredictor/biases]
is available in checkpoint, but has an incompatible shape with model
variable. Checkpoint shape: [[91]], model variable shape: [[2]]. This
variable will not be initialized from the checkpoint.
WARNING:root:Variable [SecondStageBoxPredictor/ClassPredictor/weights]
is available in checkpoint, but has an incompatible shape with model
variable. Checkpoint shape: [[1024, 91]], model variable shape:
[[1024, 2]]. This variable will not be initialized from the
checkpoint.
WARNING:root:Variable [global_step] is not available in checkpoint
WARNING:tensorflow:From
/usr/local/lib/python3.6/dist-packages/object_detection-0.1-py3.6.egg/object_detection/core/losses.py:345:
softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops)
is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.

WARNING:tensorflow:From
/usr/local/lib/python3.6/dist-packages/object_detection-0.1-py3.6.egg/object_detection/core/losses.py:345:
softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops)
is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gradients_impl.py:110:
UserWarning: Converting sparse IndexedSlices to a dense Tensor of
unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
2020-05-31 14:14:27.948004: I
tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports
instructions that this TensorFlow binary was not compiled to use: AVX2
FMA
2020-05-31 14:14:28.028247: I
tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:998] successful
NUMA node read from SysFS had negative value (-1), but there must be
at least one NUMA node, so returning NUMA node zero
2020-05-31 14:14:28.029108: I
tensorflow/compiler/xla/service/service.cc:150] XLA service 0x22ff4a0
executing computations on platform CUDA. Devices:
2020-05-31 14:14:28.029155: I
tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor
device (0): Tesla K80, Compute Capability 3.7
2020-05-31 14:14:28.031305: I
tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency:
2300000000 Hz
2020-05-31 14:14:28.031532: I
tensorflow/compiler/xla/service/service.cc:150] XLA service 0x2301180
executing computations on platform Host. Devices:
2020-05-31 14:14:28.031568: I
tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor
device (0): <undefined>, <undefined>
2020-05-31 14:14:28.031713: I
tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0
with properties:
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:04.0
totalMemory: 11.17GiB freeMemory: 11.11GiB
2020-05-31 14:14:28.031749: I
tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible
gpu devices: 0
2020-05-31 14:14:28.032818: I
tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device
interconnect StreamExecutor with strength 1 edge matrix:
2020-05-31 14:14:28.032850: I
tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0
2020-05-31 14:14:28.032871: I
tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N
2020-05-31 14:14:28.032947: W
tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:42] Overriding
allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment
variable is set. Original config value was 0.
2020-05-31 14:14:28.033000: I
tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created
TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with
10805 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus
id: 0000:00:04.0, compute capability: 3.7)
WARNING:tensorflow:From
/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py:1266:
checkpoint_exists (from
tensorflow.python.training.checkpoint_management) is deprecated and
will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
WARNING:tensorflow:From
/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py:1266:
checkpoint_exists (from
tensorflow.python.training.checkpoint_management) is deprecated and
will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
WARNING:tensorflow:From
/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py:1070:
get_checkpoint_mtimes (from
tensorflow.python.training.checkpoint_management) is deprecated and
will be removed in a future version.
Instructions for updating:
Use standard file utilities to get mtimes.
WARNING:tensorflow:From
/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py:1070:
get_checkpoint_mtimes (from
tensorflow.python.training.checkpoint_management) is deprecated and
will be removed in a future version.
Instructions for updating:
Use standard file utilities to get mtimes.
2020-05-31 14:14:38.769385: W
./tensorflow/core/grappler/optimizers/graph_optimizer_stage.h:241]
Failed to run optimizer ArithmeticOptimizer, stage
RemoveStackStridedSliceSameAxis node
Preprocessor/ResizeToRange/strided_slice_3. Error: Pack node
(Preprocessor/ResizeToRange/stack_2) axis attribute is out of bounds:
0
2020-05-31 14:14:38.916207: W
./tensorflow/core/grappler/optimizers/graph_optimizer_stage.h:241]
Failed to run optimizer ArithmeticOptimizer, stage
RemoveStackStridedSliceSameAxis node
Preprocessor/ResizeToRange/strided_slice_3. Error: Pack node
(Preprocessor/ResizeToRange/stack_2) axis attribute is out of bounds:
0
2020-05-31 14:14:38.937436: W
./tensorflow/core/grappler/optimizers/graph_optimizer_stage.h:241]
Failed to run optimizer ArithmeticOptimizer, stage
RemoveStackStridedSliceSameAxis node
Preprocessor/ResizeToRange/strided_slice_3. Error: Pack node
(Preprocessor/ResizeToRange/stack_2) axis attribute is out of bounds:
0
2020-05-31 14:14:41.371608: I
tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA
library libcublas.so.10.0 locally
2020-05-31 14:14:58.187824: E
tensorflow/core/kernels/check_numerics_op.cc:185]
abnormal_detected_host @0x2030d7f00 = {0, 1} Found Inf or NaN global
norm.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py",
line 1334, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py",
line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py",
line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Found
Inf or NaN global norm. : Tensor had Inf values
	 [[{{node VerifyFinite/CheckNumerics}}]]
	 [[{{node control_dependency}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "model_main.py", line 109, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py",
line 125, in run
    _sys.exit(main(argv))
  File "model_main.py", line 105, in main
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_specs[0])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/training.py",
line 471, in train_and_evaluate
    return executor.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/training.py",
line 611, in run
    return self.run_local()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/training.py",
line 712, in run_local
    saving_listeners=saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py",
line 358, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py",
line 1124, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py",
line 1158, in _train_model_default
    saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py",
line 1407, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py",
line 676, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py",
line 1171, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py",
line 1270, in run
    raise six.reraise(*original_exc_info)
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py",
line 1255, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py",
line 1327, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py",
line 1091, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py",
line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py",
line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py",
line 1328, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py",
line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Found
Inf or NaN global norm. : Tensor had Inf values
	 [[node VerifyFinite/CheckNumerics (defined at
/usr/local/lib/python3.6/dist-packages/object_detection-0.1-py3.6.egg/object_detection/model_lib.py:382)
]]
	 [[node control_dependency (defined at
/usr/local/lib/python3.6/dist-packages/object_detection-0.1-py3.6.egg/object_detection/model_lib.py:382)
]]

Caused by op 'VerifyFinite/CheckNumerics', defined at:
  File "model_main.py", line 109, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py",
line 125, in run
    _sys.exit(main(argv))
  File "model_main.py", line 105, in main
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_specs[0])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/training.py",
line 471, in train_and_evaluate
    return executor.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/training.py",
line 611, in run
    return self.run_local()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/training.py",
line 712, in run_local
    saving_listeners=saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py",
line 358, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py",
line 1124, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py",
line 1154, in _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py",
line 1112, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/object_detection-0.1-py3.6.egg/object_detection/model_lib.py",
line 382, in model_fn
    name='')  # Preventing scope prefix on all variables.
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/layers/python/layers/optimizers.py",
line 260, in optimize_loss
    gradients = _clip_gradients_by_norm(gradients, clip_gradients)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/layers/python/layers/optimizers.py",
line 306, in _clip_gradients_by_norm
    clipped_gradients, _ = clip_ops.clip_by_global_norm(gradients,
clip_gradients)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/clip_ops.py",
line 271, in clip_by_global_norm
    "Found Inf or NaN global norm.")
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/numerics.py",
line 44, in verify_tensor_all_finite
    return verify_tensor_all_finite_v2(t, msg, name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/numerics.py",
line 62, in verify_tensor_all_finite_v2
    verify_input = array_ops.check_numerics(x, message=message)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_array_ops.py",
line 919, in check_numerics
    "CheckNumerics", tensor=tensor, message=message, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py",
line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py",
line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py",
line 3300, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py",
line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Found Inf or NaN
global norm. : Tensor had Inf values
	 [[node VerifyFinite/CheckNumerics (defined at
/usr/local/lib/python3.6/dist-packages/object_detection-0.1-py3.6.egg/object_detection/model_lib.py:382)
]]
	 [[node control_dependency (defined at
/usr/local/lib/python3.6/dist-packages/object_detection-0.1-py3.6.egg/object_detection/model_lib.py:382)
]]

**Comment by nisarggandhewar** [comment]
Dear sir,
I managed to resolve error and my training started, I have created
inference.pb file but while performing detection using your tutorial code,
It is giving me following message and then terminated.

int() argument must be a string, a bytes-like object or a number, not 'NoneType'

kindly suggest how to resolve it.

**Comment by TannerGilbert** [comment]
This error occurs when you are passing an empty variable to the model. This can happen if you don't have a webcam connected and therefore OpenCV can't read any image. Make sure your camera is connected correctly. If you want to test the model on an image instead of a webcam stream use the [object_detection_tutorial.ipynb file](https://github.com/TannerGilbert/Tutorials/blob/master/Tensorflow%20Object%20Detection/object_detection_tutorial.ipynb) instead.

**Comment by nisarggandhewar** [comment]
Thank you very much sir, It works for me now,

While trying to open tensorboard in google colab while training with command
!tensorboard --logdir=training

it generates the following lines but not able to see tensorbaord, I even
tried !tensorboard --logdir=training --bind_all
but still not able to open tensorboard, Do I need to make any chenge in
command to open tensorboard in colab.

2020-06-02 08:33:29.394468: I
tensorflow/stream_executor/platform/default/dso_loader.cc:44]
Successfully opened dynamic library libcudart.so.10.1
W0602 08:33:31.269801 140167909897984 plugin_event_accumulator.py:332]
Found more than one graph event per run, or there was a metagraph
containing a graph_def, as well as one or more graph events.
Overwriting the graph with the newest event.
W0602 08:33:31.287763 140167909897984 plugin_event_accumulator.py:344]
Found more than one metagraph event per run. Overwriting the metagraph
with the newest event.
Serving TensorBoard on localhost; to expose to the network, use a
proxy or pass --bind_all
TensorBoard 2.2.1 at http://localhost:6006/ (Press CTRL+C to quit)

Not able to visualize tensorboard.

**Comment by nisarggandhewar** [comment]
Whether command to open tensorboard in Google co-lab is different.

**Comment by TannerGilbert** [comment]
In Google Colab you first need to execute load_ext tensorboard.

```
%load_ext tensorboard
%tensorboard --logdir training
```

**Comment by nisarggandhewar** [comment]
Dear sir,
         Thank you very much for your guidance, Your blog, video, tutorial
really help me a lot, especially your time to time suggestion.
since from installation of tensorflow api to opening tensorboard.
I search a lot for opening tensorboard in google colab but none of the
commands works properly, but your suggested command works.
again finally I want to know
how to improve performance of the model, what are important parameters
which we can alter so that performance can be improved.

Thank you.
